# Generated by Django 3.0.2 on 2020-01-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='img/mirabuk')),
            ],
        ),
    ]
    #after this perform the sql migration to create the table in postgre with the cmd 'python manage.py sqlmigrate mart(this is the app name) 0001(this is the number of the file you are in)
    #then performthe actual migration with cmd python manage.py migrate 
