# Generated by Django 3.0.2 on 2020-01-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
